### ISSUE TITLE
Comapion does not send short (single?) commands

### ISSUE THREAD

**Issue by energiebrand** [bitfocus/companion-module-dcc-ex-commandstation#1]
I'm sure about this but it seems that the Companion or the DCC-EX module doesn't send short commands like <#> or <=>. I have checked this in parallel with the EX-Installer Devoce Monitor and I cannot see any response or command comming from the Companion. Other commands like <D RAM> are running.

**Comment by daniep01** [comment]
When I create a button to send <#> and then look in the Companion log is see

```
debug: sending: <#>
debug: process: <# 50>
debug: # 50
```

If I look on DecoderPro logs I don't see these messages, but that is maybe because they are not broadcast, unlike loco commands?

**Comment by energiebrand** [comment]
OK, finally I also send the commands <1> and <0> via Companion and it really switches ON and OFF the track power. Also I can see everything in the Companion LOG including the responses from the Command Station. This means all commands are send from Companion but single charakter commands and their resonses like <#> or <=> are not shown in the Device Monitor.
That means this will be a problem in the DCC-EX Installer Device Monitor I think. So I will close this issue here.

Thanks a lot for your help!!!
